variables:
  DOCKER_BUILDKIT: 1
  RULES_CHANGES_PATH: '**/*'
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

.ssh_cloning:
  variables:
    GIT_STRATEGY: none
    KUBE_CONTEXT: default # The name to use for the new context
    AGENT_ID: 24 # replace with your agent's numeric ID
    K8S_PROXY_URL: https://git.navitech.systems/-/kubernetes-agent/k8s-proxy/
  before_script:
    - |
      if [ ! -d "${CI_PROJECT_DIR}/.git" ]
      then
          mkdir -p "${CI_PROJECT_DIR}"
          cd "${CI_PROJECT_DIR}"
          git init
          git remote add origin git@git-ssh.navitech.systems:${CI_PROJECT_PATH}.git
      fi
    - cd "${CI_PROJECT_DIR}"
    - git fetch origin
    - |
      if [ "${CI_JOB_STAGE}" = "deploy" ]
      then
          git reset HEAD --hard
      fi
    - git checkout "${CI_COMMIT_SHA}"
    - git reset --hard HEAD
    - git submodule update --init --recursive
    - |
      if [ "${CI_JOB_STAGE}" != "deploy" ]
      then
          git clean -ffdx
      fi

    - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc

stages:
  - build
  - test
  - release

.base-rules:
  extends: .ssh_cloning
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $RULES_CHANGES_PATH
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - $RULES_CHANGES_PATH
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH
      when: always
    - when: always
      allow_failure: true

include:
  - 'jobs.dev.yml'
